/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.lang.reflect.Array;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Aforcado;


/**
 *
 * @author David Marin
 */

public class VentaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form VentaPrincipal
     */
    
    Aforcado aforcado;
    //javax.swing.JLabel[] etiquetasAforcado = null;
    
    /**
     * Constructor de la ventana principal.
     */
    public VentaPrincipal() {
        initComponents();
        setLocationRelativeTo(null); //Se centra la ventana en la pantalla
        desactivarBotones();
        aforcado = null;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        fallos = new javax.swing.JPanel();
        palabraAAdivinar = new javax.swing.JLabel();
        letrasFalladas = new javax.swing.JLabel();
        palabraConGuiones = new javax.swing.JLabel();
        errores = new javax.swing.JLabel();
        e = new javax.swing.JButton();
        r = new javax.swing.JButton();
        u = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        q = new javax.swing.JButton();
        w = new javax.swing.JButton();
        t = new javax.swing.JButton();
        y = new javax.swing.JButton();
        i = new javax.swing.JButton();
        a = new javax.swing.JButton();
        s = new javax.swing.JButton();
        d = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        j = new javax.swing.JButton();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        ñ = new javax.swing.JButton();
        m = new javax.swing.JButton();
        b = new javax.swing.JButton();
        x = new javax.swing.JButton();
        c = new javax.swing.JButton();
        v = new javax.swing.JButton();
        n = new javax.swing.JButton();
        z = new javax.swing.JButton();
        Cabecera = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        botonNovaPartida = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        botonProbar = new javax.swing.JButton();
        letra = new javax.swing.JTextField();
        introduceLetra = new javax.swing.JLabel();
        LayOutDerecho = new javax.swing.JPanel();
        cabeza = new javax.swing.JLabel();
        tronco = new javax.swing.JLabel();
        brazoIzquierdo = new javax.swing.JLabel();
        brazoDerecho = new javax.swing.JLabel();
        pierna = new javax.swing.JLabel();
        Ahorcado = new javax.swing.JLabel();
        ahorcadoInicio = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1183, 650));

        fallos.setForeground(new java.awt.Color(255, 255, 255));

        palabraAAdivinar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        palabraAAdivinar.setText("Palabra a adiviñar:");

        letrasFalladas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        letrasFalladas.setText("Letras falladas:");

        palabraConGuiones.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        errores.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        errores.setForeground(new java.awt.Color(255, 51, 51));

        e.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        e.setText("E");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        r.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        r.setText("R");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        u.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        u.setText("U");
        u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uActionPerformed(evt);
            }
        });

        o.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        o.setText("O");
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });

        p.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        p.setText("P");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        q.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        q.setText("Q");
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });

        w.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        w.setText("W");
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });

        t.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t.setText("T");
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });

        y.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        y.setText("Y");
        y.setToolTipText("");
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });

        i.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        i.setText("I");
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });

        a.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        a.setText("A");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        s.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        s.setText("S");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        d.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        d.setText("D");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        f.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        f.setText("F");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        g.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        g.setText("G");
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        h.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        h.setText("H");
        h.setToolTipText("");
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });

        j.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        j.setText("J");
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });

        k.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        k.setText("K");
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });

        l.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l.setText("L");
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });

        ñ.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ñ.setText("Ñ");
        ñ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ñActionPerformed(evt);
            }
        });

        m.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        m.setText("M");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        b.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        b.setText("B");
        b.setToolTipText("");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        x.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        x.setText("X");
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        c.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        v.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        v.setText("V");
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        n.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        n.setText("N");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        z.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        z.setText("Z");
        z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fallosLayout = new javax.swing.GroupLayout(fallos);
        fallos.setLayout(fallosLayout);
        fallosLayout.setHorizontalGroup(
            fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fallosLayout.createSequentialGroup()
                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fallosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fallosLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(palabraConGuiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(fallosLayout.createSequentialGroup()
                                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fallosLayout.createSequentialGroup()
                                        .addComponent(u)
                                        .addGap(18, 18, 18)
                                        .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(w)
                                        .addGap(18, 18, 18)
                                        .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(fallosLayout.createSequentialGroup()
                                        .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(a)
                                                .addComponent(h))
                                            .addComponent(ñ, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(fallosLayout.createSequentialGroup()
                                                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(fallosLayout.createSequentialGroup()
                                                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(fallosLayout.createSequentialGroup()
                                                        .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(i, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                            .addComponent(o, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(fallosLayout.createSequentialGroup()
                                                                .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(fallosLayout.createSequentialGroup()
                                                                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(fallosLayout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(errores, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 69, Short.MAX_VALUE))))
                    .addGroup(fallosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letrasFalladas)
                            .addComponent(palabraAAdivinar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fallosLayout.setVerticalGroup(
            fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fallosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palabraConGuiones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabraAAdivinar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fallosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(letrasFalladas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b)
                        .addComponent(c)
                        .addComponent(d)
                        .addComponent(e)
                        .addComponent(f)
                        .addComponent(g))
                    .addComponent(a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(m)
                        .addComponent(n))
                    .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(h)
                        .addComponent(i)
                        .addComponent(j)
                        .addComponent(k)
                        .addComponent(l)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(o)
                        .addComponent(p)
                        .addComponent(q)
                        .addComponent(r)
                        .addComponent(s)
                        .addComponent(t))
                    .addComponent(ñ, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fallosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v)
                    .addComponent(u)
                    .addComponent(w)
                    .addComponent(x)
                    .addComponent(y)
                    .addComponent(z))
                .addGap(19, 19, 19))
        );

        getContentPane().add(fallos, java.awt.BorderLayout.LINE_START);

        titulo.setFont(new java.awt.Font("Stencil Std", 1, 48)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("O xogo do aforcado");

        javax.swing.GroupLayout CabeceraLayout = new javax.swing.GroupLayout(Cabecera);
        Cabecera.setLayout(CabeceraLayout);
        CabeceraLayout.setHorizontalGroup(
            CabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CabeceraLayout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        CabeceraLayout.setVerticalGroup(
            CabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CabeceraLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Cabecera, java.awt.BorderLayout.NORTH);

        botonNovaPartida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonNovaPartida.setText("Nova Partida");
        botonNovaPartida.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                botonNovaPartidaComponentAdded(evt);
            }
        });
        botonNovaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNovaPartidaActionPerformed(evt);
            }
        });

        BotonSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonSalir.setText("Saír");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        botonProbar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonProbar.setText("Probar");
        botonProbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonProbarMouseClicked(evt);
            }
        });
        botonProbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProbarActionPerformed(evt);
            }
        });

        letra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        letra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraActionPerformed(evt);
            }
        });

        introduceLetra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        introduceLetra.setText("Introduce unha letra:");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(introduceLetra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonProbar)
                .addGap(108, 108, 108)
                .addComponent(botonNovaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNovaPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(footerLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(introduceLetra)
                            .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonProbar))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        getContentPane().add(footer, java.awt.BorderLayout.SOUTH);

        LayOutDerecho.setLayout(new java.awt.CardLayout());

        cabeza.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cabeza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabeza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/Hangman-1.png"))); // NOI18N
        LayOutDerecho.add(cabeza, "card3");

        tronco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tronco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/Hangman-2.png"))); // NOI18N
        LayOutDerecho.add(tronco, "card4");

        brazoIzquierdo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brazoIzquierdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/Hangman-3.png"))); // NOI18N
        LayOutDerecho.add(brazoIzquierdo, "card5");

        brazoDerecho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brazoDerecho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/Hangman-4.png"))); // NOI18N
        LayOutDerecho.add(brazoDerecho, "card6");

        pierna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pierna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/Hangman-5.png"))); // NOI18N
        LayOutDerecho.add(pierna, "card7");

        Ahorcado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ahorcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/Hangman-6.png"))); // NOI18N
        LayOutDerecho.add(Ahorcado, "card8");

        ahorcadoInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ahorcadoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/Hangman-0.png"))); // NOI18N
        LayOutDerecho.add(ahorcadoInicio, "card2");

        getContentPane().add(LayOutDerecho, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón que inicia la partida y muestra el menú con las posibles opciones
    private void botonNovaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNovaPartidaActionPerformed
        String[] opcion = {"Un xogador, xerando a palabra ao azar", "Dous xogadores, introducindo a palabra a adiviñar", "Xogo por defecto"}; 
        Object jugadores = JOptionPane.showInputDialog(
                  null, // ventaá pai
                 "Seleccione un modo de xogo", // mensaxe
                 "Modo de xogo", // titulo
                  JOptionPane.QUESTION_MESSAGE, // tipo mensaxe
                  null, // icono
                  opcion, // valores
                  opcion[0] // valor marcado inicialmente
                  );
        
        if (jugadores == opcion[0]) {
            jugador1();
        } else if (jugadores == opcion[1]) {
            jugador2();
        } else if (jugadores == opcion[2]) {
            jugador3();
        }
    }//GEN-LAST:event_botonNovaPartidaActionPerformed
    //Se crea un objeto aforcado para mostrar la palabra a adivinar que se leerá de un fichero
    private void jugador1() {
        try {
            aforcado = new Aforcado(new XeradorPalabraFicheiro().xerarPalabra());
            activarBotones(); //Se activan los botones de las letras
            letra.setText("");
            reiniciarAhorcado(); //Se muestra la primera capa del ahorcado
            palabraConGuiones.setText(aforcado.amosarPalabraOculta()); //Se muestra la palabra oculta
            errores.setText(aforcado.getStringErros());//Se muestran los errores
            letra.requestFocus(); //Se coloca el cursor en el panel donde se introduce la letra manualmente
            //Si no se encuentra el fichero, el juego entra en modo por defecto.    
        } catch (XerarPalabraExcepcion ex) {
            JOptionPane.showMessageDialog(this, "Ficheiro coas palabras non atopado.\n"
                    + "Xogando coas palabras por defecto", "AVISO", JOptionPane.WARNING_MESSAGE);
            aforcado = new Aforcado(new XeradorArrayPalabras().xerarPalabra());
            activarBotones();
            letra.setText("");
            reiniciarAhorcado();
            palabraConGuiones.setText(aforcado.amosarPalabraOculta());
            errores.setText(aforcado.getStringErros());
            letra.requestFocus();
        }
    }
    //En este modo, se introducirá una ventana para poner la palabra a adivinar
    private void jugador2() {
        GUIXeradorPalabraTeclado ventanaContrasinal = new GUIXeradorPalabraTeclado();
        try {
            new XeradorPalabraFicheiro("historicoPalabras.txt").gardarPalabra(ventanaContrasinal.palabraTeclado.toLowerCase());
        } catch (XerarPalabraExcepcion ex) {
            JOptionPane.showMessageDialog(this, "Ficheiro non accesible\n"
                    + "Pecha e abre a aplicación", "AVISO", JOptionPane.WARNING_MESSAGE);
        }
        activarBotones();
        letra.setText("");
        reiniciarAhorcado();
        aforcado = new Aforcado(ventanaContrasinal.palabraTeclado.toLowerCase());
        palabraConGuiones.setText(aforcado.amosarPalabraOculta());
        errores.setText(aforcado.getStringErros());
        letra.requestFocus();
    }
    
    private void jugador3() {
        try {
            aforcado = new Aforcado(new XeradorPalabraFicheiro("historicoPalabras.txt").xerarPalabra());
            activarBotones(); //Se activan los botones de las letras
            letra.setText("");
            reiniciarAhorcado(); //Se muestra la primera capa del ahorcado
            palabraConGuiones.setText(aforcado.amosarPalabraOculta()); //Se muestra la palabra oculta
            errores.setText(aforcado.getStringErros());//Se muestran los errores
            letra.requestFocus(); //Se coloca el cursor en el panel donde se introduce la letra manualmente
            //Si no se encuentra el fichero, el juego entra en modo por defecto.    
        } catch (XerarPalabraExcepcion ex) {
            //JOptionPane.showMessageDialog(this, "Ficheiro coas palabras non atopado.\n"
            //        + "Xogando coas palabras por defecto", "AVISO", JOptionPane.WARNING_MESSAGE);
            aforcado = new Aforcado(new XeradorArrayPalabras().xerarPalabra());
            activarBotones();
            letra.setText("");
            reiniciarAhorcado();
            palabraConGuiones.setText(aforcado.amosarPalabraOculta());
            errores.setText(aforcado.getStringErros());
            letra.requestFocus();
        }
    }
    
    //Botón para confirmar que se quiere salir del programa
    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        String[] opcions = {"Si", "Non"};
        if (JOptionPane.showOptionDialog(null, "¿Está seguro?", "Confirmación saída", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opcions, opcions[1]) == JOptionPane.YES_OPTION) {
            System.exit(0);
        } 
    }//GEN-LAST:event_BotonSalirActionPerformed
    //Método que reinica el aforcado. Se muestra la primera capa del ahorcado (sin muñeco) y se activan los botones de probar y el de introducir letra
    private void reiniciarAhorcado() {
        cabeza.setVisible(false);
        tronco.setVisible(false);
        brazoIzquierdo.setVisible(false);
        brazoDerecho.setVisible(false);
        pierna.setVisible(false);
        Ahorcado.setVisible(false);
        ahorcadoInicio.setVisible(true);
        botonProbar.setEnabled(true);
        letra.setEnabled(true);
    }
    
    private void botonNovaPartidaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_botonNovaPartidaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNovaPartidaComponentAdded
    //Método que contiene otros métodos del juego
    private void amosarEstadoXogo() {
        mostrarPalabras();
        mostrarErros();
        finDoXogo();
        letra.setText("");
    }
    //Método que comprueba que la letra está en una expresión regular
    private void probarCaracter(String letraAProbar) {
        letraAProbar = letraAProbar.toLowerCase();
        if (letraAProbar.isEmpty() || !letraAProbar.matches("[a-zñáéíóúü]+")) {
            JOptionPane.showMessageDialog(this, "Introduza só letras da a á z","Error", JOptionPane.WARNING_MESSAGE);
            letraAProbar = null;
        } else if (aforcado.getStringErros().contains(letraAProbar)) {
            letra.setText("");
            JOptionPane.showMessageDialog(this, "A letra xa foi introducida","Error", JOptionPane.WARNING_MESSAGE);
        } else {
            aforcado.comprobarCaracter(letraAProbar.charAt(0));
        }
        palabraConGuiones.setText(aforcado.amosarPalabraOculta());
    }
    
    //Método que muestra la palabra oculta y los errores
    private void mostrarPalabras() {
        palabraConGuiones.setText(aforcado.amosarPalabraOculta());
        errores.setText(aforcado.getStringErros());
    }
    
    //Método que va mostrando las capas con las imágenes del ahorcado
    private void mostrarErros() {
        switch (aforcado.getErros().size()) {
            case 1:
            cabeza.setVisible(true);
            break;
            case 2:
            tronco.setVisible(true);
            break;
            case 3:
            brazoIzquierdo.setVisible(true);
            break;
            case 4:
            brazoDerecho.setVisible(true);
            break;
            case 5:
            pierna.setVisible(true);
            break;
            case 6:
            Ahorcado.setVisible(true);
            break;
        }
    }
    
    //Método que muestra el final de la partida
    private void finDoXogo() {
        if (aforcado.eFinXogo()) {
            letra.setText("");
            desactivarBotones();
            if (aforcado.maxErrosSuperado()) {
                JOptionPane.showMessageDialog(this, "Quedaches aforcado!!\nA palabra era " + aforcado.amosarPalabraCompleta(), "FIN DO XOGO", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "PARABENS!!\nA palabra era " + aforcado.amosarPalabraCompleta(), "FIN DO XOGO", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    //Método que desactiva los botones de las letras, el boton de probar y el cuadro donde se introduce la letra
    private void desactivarBotones() {
        botonProbar.setEnabled(false);
        letra.setEnabled(false);
        q.setEnabled(false);
        w.setEnabled(false);
        e.setEnabled(false);
        r.setEnabled(false);
        t.setEnabled(false);
        y.setEnabled(false);
        u.setEnabled(false);
        i.setEnabled(false);
        o.setEnabled(false);
        p.setEnabled(false);
        a.setEnabled(false);
        s.setEnabled(false);
        d.setEnabled(false);
        f.setEnabled(false);
        g.setEnabled(false);
        h.setEnabled(false);
        j.setEnabled(false);
        k.setEnabled(false);
        l.setEnabled(false);
        ñ.setEnabled(false);
        z.setEnabled(false);
        x.setEnabled(false);
        c.setEnabled(false);
        v.setEnabled(false);
        b.setEnabled(false);
        n.setEnabled(false);
        m.setEnabled(false);
    }
    
    //Método que activa los botones de las letras, el botón de probar y el cuadro donde se introduce la letra
    private void activarBotones() {
        botonProbar.setEnabled(true);
        letra.setEnabled(true);
        q.setEnabled(true);
        w.setEnabled(true);
        e.setEnabled(true);
        r.setEnabled(true);
        t.setEnabled(true);
        y.setEnabled(true);
        u.setEnabled(true);
        i.setEnabled(true);
        o.setEnabled(true);
        p.setEnabled(true);
        a.setEnabled(true);
        s.setEnabled(true);
        d.setEnabled(true);
        f.setEnabled(true);
        g.setEnabled(true);
        h.setEnabled(true);
        j.setEnabled(true);
        k.setEnabled(true);
        l.setEnabled(true);
        ñ.setEnabled(true);
        z.setEnabled(true);
        x.setEnabled(true);
        c.setEnabled(true);
        v.setEnabled(true);
        b.setEnabled(true);
        n.setEnabled(true);
        m.setEnabled(true);
    }
    
    private void letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraActionPerformed
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        letra.requestFocus();
    }//GEN-LAST:event_letraActionPerformed

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        letra.setText("q");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        q.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_qActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        letra.setText("w");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        w.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_wActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        letra.setText("e");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        e.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_eActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        letra.setText("r");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        r.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_rActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        letra.setText("t");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        t.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_tActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        letra.setText("y");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        y.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_yActionPerformed

    private void uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uActionPerformed
        letra.setText("u");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        u.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_uActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        letra.setText("i");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        i.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_iActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
        letra.setText("o");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        o.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_oActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        letra.setText("p");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        p.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_pActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        letra.setText("a");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        a.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_aActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        letra.setText("s");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        s.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_sActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        letra.setText("d");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        d.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_dActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        letra.setText("f");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        f.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        letra.setText("g");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        g.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_gActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        letra.setText("h");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        h.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_hActionPerformed

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        letra.setText("j");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        j.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_jActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        letra.setText("k");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        k.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_kActionPerformed

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        letra.setText("l");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        l.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_lActionPerformed

    private void ñActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ñActionPerformed
        letra.setText("ñ");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        ñ.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_ñActionPerformed

    private void zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zActionPerformed
        letra.setText("z");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        z.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_zActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        letra.setText("x");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        x.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_xActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        letra.setText("c");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        c.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_cActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        letra.setText("v");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        v.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_vActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        letra.setText("b");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        b.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_bActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        letra.setText("n");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        n.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_nActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        letra.setText("m");
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        m.setEnabled(false);
        letra.requestFocus();
    }//GEN-LAST:event_mActionPerformed

    private void botonProbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProbarActionPerformed
        probarCaracter(letra.getText());
        amosarEstadoXogo();
        letra.requestFocus();
    }//GEN-LAST:event_botonProbarActionPerformed

    private void botonProbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProbarMouseClicked

    }//GEN-LAST:event_botonProbarMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        int contador = 0;
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaPrincipal().setVisible(true);
            }
        });
    }
        
    
    //Fuente: https://www.iteramos.com/pregunta/29495/como-centrar-una-ventana-en-java
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ahorcado;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JPanel Cabecera;
    private javax.swing.JPanel LayOutDerecho;
    private javax.swing.JButton a;
    private javax.swing.JLabel ahorcadoInicio;
    private javax.swing.JButton b;
    private javax.swing.JButton botonNovaPartida;
    private javax.swing.JButton botonProbar;
    private javax.swing.JLabel brazoDerecho;
    private javax.swing.JLabel brazoIzquierdo;
    private javax.swing.JButton c;
    private javax.swing.JLabel cabeza;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JLabel errores;
    private javax.swing.JButton f;
    private javax.swing.JPanel fallos;
    private javax.swing.JPanel footer;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JLabel introduceLetra;
    private javax.swing.JButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JTextField letra;
    private javax.swing.JLabel letrasFalladas;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JLabel palabraAAdivinar;
    private javax.swing.JLabel palabraConGuiones;
    private javax.swing.JLabel pierna;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    private javax.swing.JButton t;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tronco;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    private javax.swing.JButton ñ;
    // End of variables declaration//GEN-END:variables
}
